Updated the assemble script

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -1,31 +1,32 @@
-#!/bin/sh
+#!/bin/bash
+set -eo pipefail
+
+
+echo "========================================="
+echo "======= Starting Custom S2I Build ======="
 
 # Uncomment to run original assemble script
 # /usr/local/s2i/assemble
 
-function get_from_nexus() {
 
 # BUNDLE_NAME="${ARTIFACT_ID}-${ARTIFACT_VERSION}.tar.gz"
 
 BUNDLE_NAME="demo-1.0-20160830.153855-28-app.tar.gz"
-  BUNDLE_FULL_PATH="${NEXUS_URL}/content/${REPOSITORY_NAME}/${GROUP_ID}/${ARTIFACT_ID}/${ARTIFACT_VERSION}/$BUNDLE_NAME"
+BUNDLE_FULL_PATH="${NEXUS_URL}/content/${REPOSITORY_NAME}/${GROUP_ID}/${ARTIFACT_ID}/${ARTIFACT_VERSION}/$BUNDLE_NAME"
   
-  echo "Started CURL Download from $BUNDLE_FULL_PATH"
-  curl -H "Accept: application/zip" $BUNDLE_FULL_PATH -o ~/$BUNDLE_NAME
-  if [ 0 -eq $? ]; then
-    echo "Download complete"
-  else
-    echo "Failed to Download Release Bundle"
-    exit 1
-  fi;
-  echo "Unzipping Tar from ~/$BUNDLE_NAME to ${DEPLOYMENTS_DIR}"
-  tar -xvzf ~/$BUNDLE_NAME -C ${DEPLOYMENTS_DIR} --strip 1
-  rm -f ~/$BUNDLE_NAME
-}
+echo "Started CURL Download from $BUNDLE_FULL_PATH"
 
-echo "========================================="
-echo "======= Starting Custom S2I Build ======="
-get_from_nexus
-echo "=== Custom code exceution is complete ==="
+curl -H "Accept: application/zip" $BUNDLE_FULL_PATH -o /deployments/$BUNDLE_NAME
+if [ 0 -eq $? ]; then
+  echo "Download complete"
+else
+  echo "Failed to Download Release Bundle"
+  exit 1
+fi;
+echo "Unpacking /deployments/$BUNDLE_NAME..."
+tar -xvzf /deployments/$BUNDLE_NAME -C /deployments --strip 1
+rm -f /tmp/$BUNDLE_NAME
+
+echo "======= Custom S2I Build Complete ======="
 echo "========================================="
 
